### ISSUE TITLE
npm test is broken

### ISSUE THREAD

**Issue by olafleur** [gregjacobs/Autolinker.js#186]
Since commit https://github.com/gregjacobs/Autolinker.js/commit/94729419549301cfbe2cf65f662535fbfb0a1f73 when I try to run `npm test` I have this error message : 

```
[23:49:12] 'doc' errored after 26 ms
[23:49:12] Error in plugin 'gulp-jsduck'
Message:
    could not find the JSDuck binary!
npm ERR! Test failed.  See above for more details.
```

Instead I use the jasmine tests page to run my tests, but it's a little less practical imho.

Am I missing something in my installation ?

**Comment by gregjacobs** [comment]
Hey, sorry about that. `npm test` was running the `gulp` command instead of `gulp test`. I updated package.json on the master branch to fix this.

JSDuck is used to create the API docs, but unfortunately it's a Ruby utility and needs to be installed separately using `gem install jsduck`. Don't worry about it though :)

**Comment by olafleur** [comment]
Super, thanks!
