### ISSUE TITLE
Can i call my custom function inside replaceFn () ?

### ISSUE THREAD

**Issue by tunathoni** [gregjacobs/Autolinker.js#244]
Hi all, i already used your lib to replace my text. Now i will to customize my hiperlink with onclick function. so the code that i expected is like this : 

```
let description = Autolinker.link(text, {
      replaceFn : function( match ) {
        switch( match.getType() ) {
            case 'url' :
            return `<a onclick="myFunc()">`+match.getAnchorText()+`</a>`
        }
      }
})
```

thanks for your help.

**Comment by gregjacobs** [comment]
Hey @tunathoni. That will work if you have a global function called `myFunc()` on your page (i.e. `window.myFunc = function() { alert('clicked'); }`)

**Comment by tunathoni** [comment]
have you tried it on vue js ? now i'm in vue js, and want to implement this lib to it.

**Comment by gregjacobs** [comment]
Ok you're probably going to have to do something different with vue. I'm not too familiar with vue, but actually Autolinker doesn't know anything about any framework or anything like that. It is simply a text processing utility: string input -> string output.

You may have to set up an event listener in your vue component and take advantage of event bubbling in order to catch clicks to the anchor tags within the component

**Comment by ptman** [comment]
Can the function called be async? Can the replaceFn be async or return a promise?
