### ISSUE TITLE
innerHtml vs innerHTML

### ISSUE THREAD

**Issue by latenssi** [gregjacobs/Autolinker.js#264]
Currently `tag.innerHtml` is undefined.

The library has shifted from using `tag.innerHtml` to `tag.innerHTML`. There are some backward compatibility efforts made but those do not include a use case where one is using the attribute by referencing it directly.

Either set `this.innerHtml` as well in the *HtmlTag* constrcutor or document the breaking change in the changelog. IMO just documenting it is better.

**Comment by gregjacobs** [comment]
Hey @latenssi. Actually neither .innerHtml or .innerHTML are intended to be public. They're just constructor config options. Use the public `.getInnerHtml()` method instead to retrieve that value. Here's the API docs on that: http://greg-jacobs.com/Autolinker.js/api/#!/api/Autolinker.HtmlTag

That being said, now that we have wonderful tools like TypeScript and ES5 setters (oh yes, Autolinker predates the wide spread availability of ES5 :)), I may expose more properties as public for easier readability and usage. I solely used methods as the public interface for everything in the past because it was a coder safety feature: if you mistype the name of a property in say, an `if` statement, then you silently get the value `undefined`, whereas if you mistype the name of a method then you get a runtime error notifying you of the problem.

Best,
Greg

**Comment by latenssi** [comment]
Alright, thanks for the response! :) 

Switched to using the interface functions.
