### ISSUE TITLE
Markdown parsing issue

### ISSUE THREAD

**Issue by yuis-ice** [gregjacobs/Autolinker.js#281]
Following is my text.
```
something 

![yuis.xsrv.jp/images/ss/ShareX_ScreenShot_41565fff-1a32-4bff-9130-86d7ec2fe1af.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_41565fff-1a32-4bff-9130-86d7ec2fe1af.png)

something
```

In the [demo page](http://greg-jacobs.com/Autolinker.js/examples/index.html), what I expected is like following as captured URL.

```
yuis.xsrv.jp/images/ss/ShareX_ScreenShot_41565fff-1a32-4bff-9130-86d7ec2fe1af.png
```

However actually, the following one is captured.

```
yuis.xsrv.jp/images/ss/ShareX_ScreenShot_41565fff-1a32-4bff-9130-86d7ec2fe1af.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_41565fff-1a32-4bff-9130-86d7ec2fe1af.png)
```

Any idea?

**Comment by gregjacobs** [comment]
Hey @yuis-ice, sorry for the delayed response.

So Autolinker isn't really supposed to be used with markdown. You'd need to first run the markdown parser on it, and then run Autolinker afterwards.

Interestingly, the `]`, `(`, and `)` characters are all valid in a URL, which is why Autolinker grabs those characters and treats them as part of the URL. A markdown parser would be needed in order to discover the beginning `![` sequence and then treat the first `]` that it encounters afterwards as the end of the URL.
