### ISSUE TITLE
Can Autolinker clean up existing links with a missing scheme?

### ISSUE THREAD

**Issue by benpowell** [gregjacobs/Autolinker.js#97]
I have the following example:

    <div id="test">
        <a href="benpowell.org">
            <span style="color:#C45911">benpowell.org</span>
        </a>
    </div>

And:

    var test = document.getElementById("test");
    var output = Autolinker.link(test.innerHTML, { newWindow: true, stripPrefix: true });
    test.innerHTML = output;

I want the output to fix the href to be:

    <a href="http://benpowell.org">

JsFiddle: http://jsfiddle.net/junto/p6yvkL4x/

Is there some option in Autolinker that can do this?

**Comment by gregjacobs** [comment]
Hey, wow, so sorry, it's long been a while since I have been able to work on the project. Unfortunately no, Autolinker can't clean that up for you. It has to assume that anything already wrapped in an `<a>` tag shouldn't be touched.

Could probably find an html parser somewhere and head down that route if you're still facing this issue though. I know it's a bit late on the response - apologies again!
